# This file was generated by GoReleaser. DO NOT EDIT.
class Gost < Formula
  desc ""
  homepage "https://github.com/ch1aki/gost"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ch1aki/gost/releases/download/v0.1.1/gost_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "67da6fd340181fc4582cf0b4cbe88ddb55531bd17caccf84c625dd3bb8c2385b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ch1aki/gost/releases/download/v0.1.1/gost_0.1.1_Linux_x86_64.tar.gz"
      sha256 "09ff45391159a27e923f8043a10347c549e29dce0a0a4402581ffdc47d312234"
    end
  end

  def install
    bin.install "gost"
  end
end
