# This file was generated by GoReleaser. DO NOT EDIT.
class Gost < Formula
  desc ""
  homepage "https://github.com/ch1aki/gost"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ch1aki/gost/releases/download/v0.0.4/gost_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "d8642d891efdacbc7128adbbc93829bfb5ee14bc4461706d7889e32d6bbb7661"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ch1aki/gost/releases/download/v0.0.4/gost_0.0.4_Linux_x86_64.tar.gz"
      sha256 "98ca75b212cd27daeeee664c8238acadc161887ba130fda06e3c86e55ed29cae"
    end
  end

  def install
    bin.install "gost"
  end
end
