# This file was generated by GoReleaser. DO NOT EDIT.
class Gost < Formula
  desc ""
  homepage "https://github.com/ch1aki/gost"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ch1aki/gost/releases/download/v0.0.4/gost_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "724ca0d69707089b153e8b5ea5249923f51d0afeee4d9d960f9d67ed02ed197d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ch1aki/gost/releases/download/v0.0.4/gost_0.0.4_Linux_x86_64.tar.gz"
      sha256 "27a9e43871643d911e2af346b5f4375795af3b8d2fae8711486eb2d1360e3a3d"
    end
  end

  def install
    bin.install "gost"
  end
end
